# Generated by Django 2.2.19 on 2023-03-07 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('id',), 'verbose_name': 'follow', 'verbose_name_plural': 'follows'},
        ),
    ]
