# Generated by Django 2.2.19 on 2023-03-07 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_sort_in_following_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
    ]
